packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@apollo/protobufjs': set this to true or false
  agent-browser: true
  esbuild: true
  mongodb-memory-server: true
  sharp: set this to true or false
